// ignore_for_file: unused_element, unused_element_parameter
part of '../canvas_templates_service.dart';

/// Layout templates: mindmap, kanban, org_chart, timeline, gantt.
final Map<String, CanvasData> _layoutTemplates = {
  'mindmap': CanvasData(
    cards: [
      CanvasCard(
        id: 'm_center',
        type: CanvasCardType.ellipse,
        x: 340,
        y: 200,
        width: 180,
        height: 100,
        title: 'Central Topic',
      ),
      CanvasCard(
        id: 'm_b1',
        type: CanvasCardType.roundedRect,
        x: 50,
        y: 50,
        width: 160,
        height: 60,
        title: 'Branch 1',
      ),
      CanvasCard(
        id: 'm_b2',
        type: CanvasCardType.roundedRect,
        x: 650,
        y: 50,
        width: 160,
        height: 60,
        title: 'Branch 2',
      ),
      CanvasCard(
        id: 'm_b3',
        type: CanvasCardType.roundedRect,
        x: 50,
        y: 350,
        width: 160,
        height: 60,
        title: 'Branch 3',
      ),
      CanvasCard(
        id: 'm_b4',
        type: CanvasCardType.roundedRect,
        x: 650,
        y: 350,
        width: 160,
        height: 60,
        title: 'Branch 4',
      ),
    ],
    connections: [
      CanvasConnection(
        id: 'mc1',
        fromCardId: 'm_center',
        toCardId: 'm_b1',
        style: CanvasConnectionStyle(pathType: ConnectionPath.curved),
      ),
      CanvasConnection(
        id: 'mc2',
        fromCardId: 'm_center',
        toCardId: 'm_b2',
        style: CanvasConnectionStyle(pathType: ConnectionPath.curved),
      ),
      CanvasConnection(
        id: 'mc3',
        fromCardId: 'm_center',
        toCardId: 'm_b3',
        style: CanvasConnectionStyle(pathType: ConnectionPath.curved),
      ),
      CanvasConnection(
        id: 'mc4',
        fromCardId: 'm_center',
        toCardId: 'm_b4',
        style: CanvasConnectionStyle(pathType: ConnectionPath.curved),
      ),
    ],
  ),
  'kanban': CanvasData(
    cards: [
      CanvasCard(
        id: 'kb_col1',
        type: CanvasCardType.swimlaneV,
        x: 0,
        y: 0,
        width: 240,
        height: 600,
        title: 'To Do',
      ),
      CanvasCard(
        id: 'kb_col2',
        type: CanvasCardType.swimlaneV,
        x: 260,
        y: 0,
        width: 240,
        height: 600,
        title: 'In Progress',
      ),
      CanvasCard(
        id: 'kb_col3',
        type: CanvasCardType.swimlaneV,
        x: 520,
        y: 0,
        width: 240,
        height: 600,
        title: 'Done',
      ),
    ],
  ),
  'org_chart': CanvasData(
    cards: [
      CanvasCard(
        id: 'oc_ceo',
        type: CanvasCardType.roundedRect,
        x: 300,
        y: 0,
        width: 160,
        height: 60,
        title: 'CEO',
      ),
      CanvasCard(
        id: 'oc_cto',
        type: CanvasCardType.roundedRect,
        x: 120,
        y: 120,
        width: 160,
        height: 60,
        title: 'CTO',
      ),
      CanvasCard(
        id: 'oc_cfo',
        type: CanvasCardType.roundedRect,
        x: 480,
        y: 120,
        width: 160,
        height: 60,
        title: 'CFO',
      ),
      CanvasCard(
        id: 'oc_dev1',
        type: CanvasCardType.roundedRect,
        x: 30,
        y: 240,
        width: 140,
        height: 50,
        title: 'Dev Lead',
      ),
      CanvasCard(
        id: 'oc_dev2',
        type: CanvasCardType.roundedRect,
        x: 200,
        y: 240,
        width: 140,
        height: 50,
        title: 'QA Lead',
      ),
      CanvasCard(
        id: 'oc_acc',
        type: CanvasCardType.roundedRect,
        x: 420,
        y: 240,
        width: 140,
        height: 50,
        title: 'Accounting',
      ),
      CanvasCard(
        id: 'oc_hr',
        type: CanvasCardType.roundedRect,
        x: 590,
        y: 240,
        width: 140,
        height: 50,
        title: 'HR',
      ),
    ],
    connections: [
      CanvasConnection(
        id: 'occ1',
        fromCardId: 'oc_ceo',
        toCardId: 'oc_cto',
        fromSide: ConnectionSide.bottom,
        toSide: ConnectionSide.top,
      ),
      CanvasConnection(
        id: 'occ2',
        fromCardId: 'oc_ceo',
        toCardId: 'oc_cfo',
        fromSide: ConnectionSide.bottom,
        toSide: ConnectionSide.top,
      ),
      CanvasConnection(
        id: 'occ3',
        fromCardId: 'oc_cto',
        toCardId: 'oc_dev1',
        fromSide: ConnectionSide.bottom,
        toSide: ConnectionSide.top,
      ),
      CanvasConnection(
        id: 'occ4',
        fromCardId: 'oc_cto',
        toCardId: 'oc_dev2',
        fromSide: ConnectionSide.bottom,
        toSide: ConnectionSide.top,
      ),
      CanvasConnection(
        id: 'occ5',
        fromCardId: 'oc_cfo',
        toCardId: 'oc_acc',
        fromSide: ConnectionSide.bottom,
        toSide: ConnectionSide.top,
      ),
      CanvasConnection(
        id: 'occ6',
        fromCardId: 'oc_cfo',
        toCardId: 'oc_hr',
        fromSide: ConnectionSide.bottom,
        toSide: ConnectionSide.top,
      ),
    ],
  ),
  'timeline': CanvasData(
    cards: [
      CanvasCard(
        id: 'tl_1',
        type: CanvasCardType.roundedRect,
        x: 0,
        y: 80,
        width: 140,
        height: 60,
        title: 'Phase 1',
      ),
      CanvasCard(
        id: 'tl_2',
        type: CanvasCardType.roundedRect,
        x: 180,
        y: 80,
        width: 140,
        height: 60,
        title: 'Phase 2',
      ),
      CanvasCard(
        id: 'tl_3',
        type: CanvasCardType.roundedRect,
        x: 360,
        y: 80,
        width: 140,
        height: 60,
        title: 'Phase 3',
      ),
      CanvasCard(
        id: 'tl_4',
        type: CanvasCardType.roundedRect,
        x: 540,
        y: 80,
        width: 140,
        height: 60,
        title: 'Phase 4',
      ),
    ],
    connections: [
      CanvasConnection(
        id: 'tlc1',
        fromCardId: 'tl_1',
        toCardId: 'tl_2',
        fromSide: ConnectionSide.right,
        toSide: ConnectionSide.left,
      ),
      CanvasConnection(
        id: 'tlc2',
        fromCardId: 'tl_2',
        toCardId: 'tl_3',
        fromSide: ConnectionSide.right,
        toSide: ConnectionSide.left,
      ),
      CanvasConnection(
        id: 'tlc3',
        fromCardId: 'tl_3',
        toCardId: 'tl_4',
        fromSide: ConnectionSide.right,
        toSide: ConnectionSide.left,
      ),
    ],
  ),
  'gantt': CanvasData(
    cards: [
      CanvasCard(
        id: 'gt_header',
        type: CanvasCardType.swimlaneH,
        x: 0,
        y: 0,
        width: 800,
        height: 400,
        title: 'Gantt Chart',
      ),
    ],
  ),
};
