// ignore_for_file: unused_element, unused_element_parameter
part of '../canvas_templates_service.dart';

/// Flow-related templates: flowchart, swimlane, state_machine, decision_tree.
final Map<String, CanvasData> _flowTemplates = {
  'flowchart': CanvasData(
    cards: [
      CanvasCard(
        id: 't_start',
        type: CanvasCardType.roundedRect,
        x: 300,
        y: 0,
        width: 120,
        height: 50,
        title: 'Start',
      ),
      CanvasCard(
        id: 't_process',
        type: CanvasCardType.rectangle,
        x: 280,
        y: 100,
        width: 160,
        height: 60,
        title: 'Process',
      ),
      CanvasCard(
        id: 't_decision',
        type: CanvasCardType.diamond,
        x: 270,
        y: 220,
        width: 180,
        height: 120,
        title: 'Decision?',
      ),
      CanvasCard(
        id: 't_action_a',
        type: CanvasCardType.rectangle,
        x: 100,
        y: 400,
        width: 160,
        height: 60,
        title: 'Action A',
      ),
      CanvasCard(
        id: 't_action_b',
        type: CanvasCardType.rectangle,
        x: 460,
        y: 400,
        width: 160,
        height: 60,
        title: 'Action B',
      ),
      CanvasCard(
        id: 't_end',
        type: CanvasCardType.roundedRect,
        x: 300,
        y: 540,
        width: 120,
        height: 50,
        title: 'End',
      ),
    ],
    connections: [
      CanvasConnection(
        id: 'tc1',
        fromCardId: 't_start',
        toCardId: 't_process',
        fromSide: ConnectionSide.bottom,
        toSide: ConnectionSide.top,
      ),
      CanvasConnection(
        id: 'tc2',
        fromCardId: 't_process',
        toCardId: 't_decision',
        fromSide: ConnectionSide.bottom,
        toSide: ConnectionSide.top,
      ),
      CanvasConnection(
        id: 'tc3',
        fromCardId: 't_decision',
        toCardId: 't_action_a',
        fromSide: ConnectionSide.left,
        toSide: ConnectionSide.top,
        label: 'Yes',
      ),
      CanvasConnection(
        id: 'tc4',
        fromCardId: 't_decision',
        toCardId: 't_action_b',
        fromSide: ConnectionSide.right,
        toSide: ConnectionSide.top,
        label: 'No',
      ),
      CanvasConnection(
        id: 'tc5',
        fromCardId: 't_action_a',
        toCardId: 't_end',
        fromSide: ConnectionSide.bottom,
        toSide: ConnectionSide.left,
      ),
      CanvasConnection(
        id: 'tc6',
        fromCardId: 't_action_b',
        toCardId: 't_end',
        fromSide: ConnectionSide.bottom,
        toSide: ConnectionSide.right,
      ),
    ],
  ),
  'swimlane': CanvasData(
    cards: [
      CanvasCard(
        id: 's_lane',
        type: CanvasCardType.swimlaneH,
        x: 0,
        y: 0,
        width: 800,
        height: 400,
        title: 'Process Flow',
      ),
    ],
  ),
  'state_machine': CanvasData(
    cards: [
      CanvasCard(
        id: 'sm_init',
        type: CanvasCardType.ellipse,
        x: 300,
        y: 0,
        width: 100,
        height: 50,
        title: 'Init',
      ),
      CanvasCard(
        id: 'sm_idle',
        type: CanvasCardType.roundedRect,
        x: 280,
        y: 120,
        width: 140,
        height: 60,
        title: 'Idle',
      ),
      CanvasCard(
        id: 'sm_active',
        type: CanvasCardType.roundedRect,
        x: 280,
        y: 260,
        width: 140,
        height: 60,
        title: 'Active',
      ),
      CanvasCard(
        id: 'sm_paused',
        type: CanvasCardType.roundedRect,
        x: 80,
        y: 260,
        width: 140,
        height: 60,
        title: 'Paused',
      ),
      CanvasCard(
        id: 'sm_done',
        type: CanvasCardType.ellipse,
        x: 280,
        y: 400,
        width: 140,
        height: 60,
        title: 'Done',
      ),
      CanvasCard(
        id: 'sm_error',
        type: CanvasCardType.diamond,
        x: 500,
        y: 260,
        width: 140,
        height: 100,
        title: 'Error',
      ),
    ],
    connections: [
      CanvasConnection(
        id: 'smc1',
        fromCardId: 'sm_init',
        toCardId: 'sm_idle',
        fromSide: ConnectionSide.bottom,
        toSide: ConnectionSide.top,
      ),
      CanvasConnection(
        id: 'smc2',
        fromCardId: 'sm_idle',
        toCardId: 'sm_active',
        fromSide: ConnectionSide.bottom,
        toSide: ConnectionSide.top,
        label: 'start',
      ),
      CanvasConnection(
        id: 'smc3',
        fromCardId: 'sm_active',
        toCardId: 'sm_paused',
        fromSide: ConnectionSide.left,
        toSide: ConnectionSide.right,
        label: 'pause',
      ),
      CanvasConnection(
        id: 'smc4',
        fromCardId: 'sm_paused',
        toCardId: 'sm_active',
        fromSide: ConnectionSide.right,
        toSide: ConnectionSide.left,
        label: 'resume',
      ),
      CanvasConnection(
        id: 'smc5',
        fromCardId: 'sm_active',
        toCardId: 'sm_done',
        fromSide: ConnectionSide.bottom,
        toSide: ConnectionSide.top,
        label: 'finish',
      ),
      CanvasConnection(
        id: 'smc6',
        fromCardId: 'sm_active',
        toCardId: 'sm_error',
        fromSide: ConnectionSide.right,
        toSide: ConnectionSide.left,
        label: 'error',
      ),
      CanvasConnection(
        id: 'smc7',
        fromCardId: 'sm_error',
        toCardId: 'sm_idle',
        fromSide: ConnectionSide.top,
        toSide: ConnectionSide.right,
        label: 'reset',
      ),
    ],
  ),
  'decision_tree': CanvasData(
    cards: [
      CanvasCard(
        id: 'dt_root',
        type: CanvasCardType.diamond,
        x: 270,
        y: 0,
        width: 180,
        height: 120,
        title: 'Condition?',
      ),
      CanvasCard(
        id: 'dt_y1',
        type: CanvasCardType.diamond,
        x: 50,
        y: 200,
        width: 180,
        height: 120,
        title: 'Check A?',
      ),
      CanvasCard(
        id: 'dt_n1',
        type: CanvasCardType.diamond,
        x: 490,
        y: 200,
        width: 180,
        height: 120,
        title: 'Check B?',
      ),
      CanvasCard(
        id: 'dt_yy',
        type: CanvasCardType.roundedRect,
        x: 0,
        y: 400,
        width: 120,
        height: 50,
        title: 'Result 1',
      ),
      CanvasCard(
        id: 'dt_yn',
        type: CanvasCardType.roundedRect,
        x: 160,
        y: 400,
        width: 120,
        height: 50,
        title: 'Result 2',
      ),
      CanvasCard(
        id: 'dt_ny',
        type: CanvasCardType.roundedRect,
        x: 440,
        y: 400,
        width: 120,
        height: 50,
        title: 'Result 3',
      ),
      CanvasCard(
        id: 'dt_nn',
        type: CanvasCardType.roundedRect,
        x: 600,
        y: 400,
        width: 120,
        height: 50,
        title: 'Result 4',
      ),
    ],
    connections: [
      CanvasConnection(
        id: 'dtc1',
        fromCardId: 'dt_root',
        toCardId: 'dt_y1',
        fromSide: ConnectionSide.left,
        toSide: ConnectionSide.top,
        label: 'Yes',
      ),
      CanvasConnection(
        id: 'dtc2',
        fromCardId: 'dt_root',
        toCardId: 'dt_n1',
        fromSide: ConnectionSide.right,
        toSide: ConnectionSide.top,
        label: 'No',
      ),
      CanvasConnection(
        id: 'dtc3',
        fromCardId: 'dt_y1',
        toCardId: 'dt_yy',
        fromSide: ConnectionSide.left,
        toSide: ConnectionSide.top,
        label: 'Yes',
      ),
      CanvasConnection(
        id: 'dtc4',
        fromCardId: 'dt_y1',
        toCardId: 'dt_yn',
        fromSide: ConnectionSide.right,
        toSide: ConnectionSide.top,
        label: 'No',
      ),
      CanvasConnection(
        id: 'dtc5',
        fromCardId: 'dt_n1',
        toCardId: 'dt_ny',
        fromSide: ConnectionSide.left,
        toSide: ConnectionSide.top,
        label: 'Yes',
      ),
      CanvasConnection(
        id: 'dtc6',
        fromCardId: 'dt_n1',
        toCardId: 'dt_nn',
        fromSide: ConnectionSide.right,
        toSide: ConnectionSide.top,
        label: 'No',
      ),
    ],
  ),
};
