// ignore_for_file: unused_element, unused_element_parameter
part of '../canvas_templates_service.dart';

/// Diagram templates: uml_class, er_diagram, network, venn.
final Map<String, CanvasData> _diagramTemplates = {
  'uml_class': CanvasData(
    cards: [
      CanvasCard(
        id: 'u_base',
        type: CanvasCardType.rectangle,
        x: 200,
        y: 0,
        width: 200,
        height: 60,
        title: 'BaseClass',
        content: '+ method(): void',
      ),
      CanvasCard(
        id: 'u_child1',
        type: CanvasCardType.rectangle,
        x: 50,
        y: 200,
        width: 200,
        height: 60,
        title: 'ChildClass1',
        content: '+ override(): void',
      ),
      CanvasCard(
        id: 'u_child2',
        type: CanvasCardType.rectangle,
        x: 350,
        y: 200,
        width: 200,
        height: 60,
        title: 'ChildClass2',
        content: '+ newMethod(): int',
      ),
      CanvasCard(
        id: 'u_iface',
        type: CanvasCardType.roundedRect,
        x: 200,
        y: -160,
        width: 200,
        height: 60,
        title: '<<interface>>',
        content: '+ contract(): bool',
      ),
    ],
    connections: [
      CanvasConnection(
        id: 'uc1',
        fromCardId: 'u_child1',
        toCardId: 'u_base',
        fromSide: ConnectionSide.top,
        toSide: ConnectionSide.bottom,
        style: CanvasConnectionStyle(
          pathType: ConnectionPath.orthogonal,
          arrowStyle: ArrowStyle.triangle,
        ),
      ),
      CanvasConnection(
        id: 'uc2',
        fromCardId: 'u_child2',
        toCardId: 'u_base',
        fromSide: ConnectionSide.top,
        toSide: ConnectionSide.bottom,
        style: CanvasConnectionStyle(
          pathType: ConnectionPath.orthogonal,
          arrowStyle: ArrowStyle.triangle,
        ),
      ),
      CanvasConnection(
        id: 'uc3',
        fromCardId: 'u_base',
        toCardId: 'u_iface',
        fromSide: ConnectionSide.top,
        toSide: ConnectionSide.bottom,
        style: CanvasConnectionStyle(
          pathType: ConnectionPath.orthogonal,
          arrowStyle: ArrowStyle.triangle,
          startArrowStyle: ArrowStyle.triangle,
        ),
      ),
    ],
  ),
  'er_diagram': CanvasData(
    cards: [
      CanvasCard(
        id: 'er_user',
        type: CanvasCardType.rectangle,
        x: 100,
        y: 50,
        width: 180,
        height: 120,
        title: 'User',
        content: 'id: PK\nname: VARCHAR\nemail: VARCHAR',
      ),
      CanvasCard(
        id: 'er_order',
        type: CanvasCardType.rectangle,
        x: 450,
        y: 50,
        width: 180,
        height: 120,
        title: 'Order',
        content: 'id: PK\nuser_id: FK\ntotal: DECIMAL',
      ),
      CanvasCard(
        id: 'er_product',
        type: CanvasCardType.rectangle,
        x: 450,
        y: 300,
        width: 180,
        height: 120,
        title: 'Product',
        content: 'id: PK\nname: VARCHAR\nprice: DECIMAL',
      ),
      CanvasCard(
        id: 'er_item',
        type: CanvasCardType.diamond,
        x: 250,
        y: 300,
        width: 160,
        height: 100,
        title: 'OrderItem',
      ),
    ],
    connections: [
      CanvasConnection(
        id: 'erc1',
        fromCardId: 'er_user',
        toCardId: 'er_order',
        fromSide: ConnectionSide.right,
        toSide: ConnectionSide.left,
        label: '1:N',
      ),
      CanvasConnection(
        id: 'erc2',
        fromCardId: 'er_order',
        toCardId: 'er_item',
        fromSide: ConnectionSide.bottom,
        toSide: ConnectionSide.top,
        label: '1:N',
      ),
      CanvasConnection(
        id: 'erc3',
        fromCardId: 'er_product',
        toCardId: 'er_item',
        fromSide: ConnectionSide.left,
        toSide: ConnectionSide.right,
        label: '1:N',
      ),
    ],
  ),
  'network': CanvasData(
    cards: [
      CanvasCard(
        id: 'n_cloud',
        type: CanvasCardType.ellipse,
        x: 300,
        y: 0,
        width: 200,
        height: 80,
        title: 'Cloud / Internet',
      ),
      CanvasCard(
        id: 'n_fw',
        type: CanvasCardType.hexagon,
        x: 320,
        y: 150,
        width: 160,
        height: 80,
        title: 'Firewall',
      ),
      CanvasCard(
        id: 'n_lb',
        type: CanvasCardType.diamond,
        x: 320,
        y: 300,
        width: 160,
        height: 100,
        title: 'Load Balancer',
      ),
      CanvasCard(
        id: 'n_srv1',
        type: CanvasCardType.cylinder,
        x: 150,
        y: 480,
        width: 140,
        height: 100,
        title: 'Server 1',
      ),
      CanvasCard(
        id: 'n_srv2',
        type: CanvasCardType.cylinder,
        x: 510,
        y: 480,
        width: 140,
        height: 100,
        title: 'Server 2',
      ),
      CanvasCard(
        id: 'n_db',
        type: CanvasCardType.cylinder,
        x: 330,
        y: 650,
        width: 140,
        height: 100,
        title: 'Database',
      ),
    ],
    connections: [
      CanvasConnection(
        id: 'nc1',
        fromCardId: 'n_cloud',
        toCardId: 'n_fw',
        fromSide: ConnectionSide.bottom,
        toSide: ConnectionSide.top,
      ),
      CanvasConnection(
        id: 'nc2',
        fromCardId: 'n_fw',
        toCardId: 'n_lb',
        fromSide: ConnectionSide.bottom,
        toSide: ConnectionSide.top,
      ),
      CanvasConnection(
        id: 'nc3',
        fromCardId: 'n_lb',
        toCardId: 'n_srv1',
        fromSide: ConnectionSide.left,
        toSide: ConnectionSide.top,
        label: '',
      ),
      CanvasConnection(
        id: 'nc4',
        fromCardId: 'n_lb',
        toCardId: 'n_srv2',
        fromSide: ConnectionSide.right,
        toSide: ConnectionSide.top,
        label: '',
      ),
      CanvasConnection(
        id: 'nc5',
        fromCardId: 'n_srv1',
        toCardId: 'n_db',
        fromSide: ConnectionSide.bottom,
        toSide: ConnectionSide.left,
      ),
      CanvasConnection(
        id: 'nc6',
        fromCardId: 'n_srv2',
        toCardId: 'n_db',
        fromSide: ConnectionSide.bottom,
        toSide: ConnectionSide.right,
      ),
    ],
  ),
  'venn': CanvasData(
    cards: [
      CanvasCard(
        id: 'vn_a',
        type: CanvasCardType.ellipse,
        x: 100,
        y: 100,
        width: 250,
        height: 250,
        title: 'Set A',
        colorValue: 0xFFE3F2FD,
      ),
      CanvasCard(
        id: 'vn_b',
        type: CanvasCardType.ellipse,
        x: 300,
        y: 100,
        width: 250,
        height: 250,
        title: 'Set B',
        colorValue: 0xFFFCE4EC,
      ),
      CanvasCard(
        id: 'vn_c',
        type: CanvasCardType.ellipse,
        x: 200,
        y: 280,
        width: 250,
        height: 250,
        title: 'Set C',
        colorValue: 0xFFE8F5E9,
      ),
    ],
  ),
};
