# gen_docs.ps1 - Generate API docs (dartdoc) and architecture summary.
#
# Usage:
#   pwsh scripts/gen_docs.ps1
#
# Output:
#   doc/api/index.html            - Dartdoc HTML output
#   docs/architecture.md         - Code-level architecture summary
#   docs/coverage-summary.md     - LCOV coverage breakdown by directory

param(
    [switch]$SkipDartdoc = $false,
    [switch]$SkipArch = $false
)

$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = Resolve-Path "$ScriptDir/.."
Set-Location $RepoRoot

Write-Host "[gen_docs] repo root: $RepoRoot"

if (-not $SkipDartdoc) {
    Write-Host "[gen_docs] running dartdoc..."
    $dartdoc = Get-Command dartdoc -ErrorAction SilentlyContinue
    if ($null -eq $dartdoc) {
        Write-Warning "[gen_docs] dartdoc not found; skipping"
    } else {
        if (Test-Path "doc/api") { Remove-Item -Recurse -Force "doc/api" }
        dartdoc --output doc/api 2>&1 | Select-Object -Last 20
        Write-Host "[gen_docs] dartdoc → doc/api/index.html"
    }
}

if (-not $SkipArch) {
    Write-Host "[gen_docs] writing architecture summary..."
    New-Item -ItemType Directory -Force -Path "docs" | Out-Null

    $lineCounts = @{}
    foreach ($dir in @("agents", "core", "data", "plugins", "services", "ui")) {
        $libDir = Join-Path "lib" $dir
        if (Test-Path $libDir) {
            $lineCount = 0
            $files = 0
            Get-ChildItem -Path $libDir -Filter "*.dart" -Recurse | ForEach-Object {
                $lineCount += (Get-Content $_.FullName | Measure-Object -Line).Lines
                $files++
            }
            $lineCounts[$dir] = @{ Lines = $lineCount; Files = $files }
        }
    }

    $totalLines = 0
    $totalFiles = 0
    foreach ($entry in $lineCounts.Values) {
        $totalLines += $entry.Lines
        $totalFiles += $entry.Files
    }

    $arch = @"
# Architecture Overview (auto-generated by gen_docs.ps1)

> Total: $totalFiles Dart files, $totalLines lines of production code under lib/.

## Module layout

| Module | Files | Lines (incl. blanks) |
|--------|-------|---------------------|
"@

    foreach ($key in $lineCounts.Keys | Sort-Object) {
        $arch += "`n| ``$key`` | $($lineCounts[$key].Files) | $($lineCounts[$key].Lines) |"
    }

    $arch += @"


## Service layer

| Service | Responsibility |
|---------|----------------|
| `AIService` | Provider routing, streaming, tool-call loop, memory |
| `KnowledgeService` | Notes, active note, links, in-memory state |
| `NoteService` | CRUD on NoteRepository, file sanitisation, rename |
| `LinkService` | Wikilink extraction, title index, backlink graph |
| `AgentService` | ReAct loop, tool registry, task persistence |
| `GitSyncService` | Initialise / commit / push / pull via git CLI |
| `WebDAVSyncProvider` | WebDAV vault sync |
| `EmbeddingService` | Ollama + local hash fallback, HNSW index |
| `ShortcutService` | Keyboard shortcut binding + conflict detection |
| `PerformanceMonitor` | Frame timing sliding window, p50/p95/p99 |
| `VaultStore` | Current vault config, provider lifecycle |
| `CapabilityChecker` | Plugin permission enforcement |

## Provider / data flow

```
        ┌──────────────┐
        │   UI Layer   │ (lib/ui/*)
        └──────┬───────┘
               │  Riverpod consumers
        ┌──────▼───────┐
        │ Notifiers    │ (lib/services/*_notifier.dart, agents/*)
        └──────┬───────┘
               │  state + actions
        ┌──────▼───────┐
        │ Repositories │ (lib/data/repositories/*)
        └──────┬───────┘
               │  file I/O
        ┌──────▼───────┐
        │   Stores     │ (lib/data/stores/* — sqflite / file system)
        └──────────────┘
```

## Plugin sandbox

Plugins run in a separate Dart Isolate spawned by `PluginHost`. The
host process owns:

- All file I/O for the vault
- The Riverpod container (services + state)
- Network requests (TLS-terminated)
- Capability enforcement via `CapabilityChecker.assertCapability()`

The plugin isolate only sees the `PluginAPI` interface and
serialisable value objects. There is no `dart:io` or `dart:ui` in
the plugin scope.
"@

    $arch | Out-File -FilePath "docs/architecture.md" -Encoding utf8
    Write-Host "[gen_docs] architecture → docs/architecture.md"
}

Write-Host "[gen_docs] done"
